"""empty message

Revision ID: 17101320d39e
Revises: fdeee95a406f
Create Date: 2020-11-27 21:21:49.033595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17101320d39e'
down_revision = 'fdeee95a406f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_menu_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=30), nullable=True),
    sa.Column('callback', sa.String(length=30), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_menu_items')
    # ### end Alembic commands ###
